" DEBUG for vim :messages

source <sfile>:p:h/basic/basic.vim
source <sfile>:p:h/basic/keymap.vim
source <sfile>:p:h/basic/autocmds.vim
source <sfile>:p:h/basic/markdown.vim

source <sfile>:p:h/plugin/plugins.vim
source <sfile>:p:h/basic/colorscheme.vim  " colorscheme after plug loaded
